name: Run CI on main

on:
  push:
    branches: [main]

jobs:
  ci:
    uses: ./.github/workflows/nodejs-ci.yml
    with:
      node-version: "24"
      working-directory: "."
      run-integration-tests: true
      upload-coverage: false
